# Generated by Django 5.2.7 on 2025-10-29 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_coupon_once_per_customer_alter_address_postal_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='shop',
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
