# Generated by Django 5.2.7 on 2025-10-29 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_customer_address_address_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppaymentmethod',
            name='gateway_payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_payment_methods', to='cart.gatewaypaymentmethod'),
        ),
    ]
