# Generated by Django 5.2.7 on 2025-10-30 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_address_updated_at_alter_coupon_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], db_index=True, default='unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('shipped', 'Shipped'), ('cancelled', 'Cancelled'), ('delivered', 'Delivered')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='shop',
            name='domain',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='coupon',
            unique_together={('shop', 'code')},
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['shop', 'is_active'], name='cart_coupon_shop_id_ac4c44_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['shop', 'email'], name='cart_custom_shop_id_7319af_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['purchase', 'status'], name='cart_paymen_purchas_81fbd6_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'transaction_reference'], name='cart_paymen_status_664303_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['shop', 'sku'], name='cart_produc_shop_id_f8b614_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['shop', 'is_active'], name='cart_produc_shop_id_64f54b_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['shop', 'status'], name='cart_purcha_shop_id_fc2476_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['shop', 'customer'], name='cart_purcha_shop_id_c0c542_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['shop', 'created_at'], name='cart_purcha_shop_id_915cea_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseproduct',
            index=models.Index(fields=['purchase', 'product'], name='cart_purcha_purchas_801173_idx'),
        ),
    ]
